name: NodeJS CI

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Démarrer le serveur
        run: |
          npm run prod &
          sleep 10

  test:
    needs: build

    runs-on: self-hosted
    
    steps:
      - name: Tester l'API
        run: echo "SUCCESS !"
      - run: echo ${{ secrets.PWD }}
      - run: echo ${{ secrets.EMAIL }}
      - run: echo ${{ vars.NAME }}
      - run: curl http://localhost:3000/api