name: Premier Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message
        run: echo "Bonjour Github Actions"
  
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      
      - name: Afficher le working directory
        run: pwd
      
      - name: Afficher tous les fichier
        run: ls ../